### ISSUE TITLE
Loading too early?

### ISSUE THREAD

**Issue by auwsmit** [zonuexe/init-open-recentf.el#1]
When I use this package, it shows up before Emacs has updated its font or maximized the window. As soon as I close the window, the font is updated and window maximized. 

Is there a way to delay the first time, or to guarantee that it runs after my settings have loaded?

Version: Emacs 24.5.1 on Windows 10

**Comment by zonuexe** [comment]
@AssailantLF 
Hi. I looked your emacs config.
https://github.com/AssailantLF/emacsconfig/blob/master/config.org#maximize-emacs-on-startup

You seems to be using `window-setup-hook`.  Please try using the ~~`init-open-recentf-after-hook`~~  `init-open-recentf-before-hook` to it instead.

For example:

``` el
(if (eq system-type 'windows-nt)
    (add-hook 'init-open-recentf-after-hook 'w32-maximize-frame t)
  (set-frame-parameter nil 'fullscreen 'maximized))
```

This order is related to the start-up process of Emacs.
If you are interested in Emacs Lisp, please consider reading this code.
https://github.com/emacs-mirror/emacs/blob/master/lisp/startup.el

**Comment by auwsmit** [comment]
Hm.. when I switch it to `init-open-recentf-after-hook`, it does the same thing, except it doesn't maximize at all. `init-open-recentf-before-hook` appears to work, but the font still isn't updated, and when I open a file, the maximized window strangely un-maximizes. This is probably due to some package or setting that I have, but I don't know for sure.

Here's my `use-package` block, if that helps:

```
(use-package init-open-recentf
  :init
  (setq init-open-recentf-function #'ivy-recentf)
  :config
  (if (eq system-type 'windows-nt)
      (progn
        (add-hook 'init-open-recentf-after-hook 'w32-maximize-frame t))
    (set-frame-parameter nil 'fullscreen 'maximized))

  (init-open-recentf))
```

When I have some time, I'll do some testing with a bare-bones config to see if I can find the problem for sure.

**Comment by zonuexe** [comment]
@AssailantLF 
Sorry, use `init-open-recentf-before-hook`.

**Comment by auwsmit** [comment]
Yeah, `init-open-recentf-before-hook` appears to work at first, but the font still isn't updated, and when I open a file (or cancel), the maximized window shrinks, but still thinks it's maximized.

It's probably more of an issue with the method I'm using to maximize rather than this package. I'll try looking into alternative methods.
